var __CONSTANTS = {
  months: [
    { name: "Enero", short: "Ene", numDays: 31 },
    { name: "Febrero", short: "Feb", numDays: 29 },
    { name: "Marzo", short: "Mar", numDays: 31 },
    { name: "Abril", short: "Abr", numDays: 30 },
    { name: "Mayo", short: "May", numDays: 31 },
    { name: "Junio", short: "Jun", numDays: 30 },
    { name: "Julio", short: "Jul", numDays: 31 },
    { name: "Agosto", short: "Ago", numDays: 31 },
    { name: "Setiembre", short: "Sep", numDays: 30 },
    { name: "Octubre", short: "Oct", numDays: 31 },
    { name: "Noviembre", short: "Nov", numDays: 30 },
    { name: "Diciembre", short: "Dic", numDays: 31 },
  ],
  days: [
    { name: "Domingo", short: "Dom", min: "Do" },
    { name: "Lunes", short: "Lun", min: "Lu" },
    { name: "Martes", short: "Mar", min: "Ma" },
    { name: "Miércoles", short: "Mié", min: "Mi" },
    { name: "Jueves", short: "Jue", min: "Ju" },
    { name: "Viernes", short: "Vie", min: "Vi" },
    { name: "Sábado", short: "Sáb", min: "Sá" },
  ],
};
